kraken/apps/core/urls.py
from django.conf.urls import patterns, url
from django.contrib import admin
from kraken.apps.core import views

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.landing, name="landing"),
    url(r'^home/$', views.home, name="home"),
    url(r'^signin/$', views.sign_in, name="sign_in"),
    url(r'^signout/$', views.sign_out, name="sign_out"),

    url(r'^client/create/$', views.create_client, name='create_client')
)

kraken/apps/help/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('kraken.apps.help.views',
                       url(r'^guide/$', 'help_guide', name='help_guide'),
                       url(r'^faq/$', 'help_faq', name='help_faq'),
                       )

kraken/apps/schemas/urls.py
from django.conf.urls import patterns, url

from kraken.apps.schemas import views

urlpatterns = patterns('kraken.apps.schemas.views',
                       url(r'^clients/(?P<client_id>\d+)/schemas/create/$', 'create_schema', name='create_schema'),
                       url(r'^clients/(?P<client_id>\d+)/schemas/(?P<schema_id>\d+)/versions/(?P<version_id>\d+)/edit/$', 'edit_version', name='edit_version'),
                       url(r'^clients/(?P<client_id>\d+)/schemas/(?P<schema_id>\d+)/versions/(?P<version_id>\d+)/files/create/$', 'create_file', name='create_file'),
                       url(r'^clients/(?P<client_id>\d+)/schemas/(?P<schema_id>\d+)/versions/(?P<version_id>\d+)/files/(?P<file_id>\d+)/edit/$', 'edit_file', name='edit_file'),

                       url(r'^client/(?P<client_name>\w+)/schemas/$', views.client_schemas_list, name='client_schemas_list'),
                       url(r'^client/(?P<client_name>\w+)/schema/(?P<schema_name>\w+)/versions/$', views.schema_versions_list, name='schema_versions_list'),
                       url(r'^schemas/batch_files/$', 'batch_files', name='batch_files'),

                       )

kraken/apps/users/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('kraken.apps.users.views',
    url(r'^user_management/$', 'user_management', name='user_management'),
    url(r'^user_update/(?P<user_id>\d+)/$', 'user_update', name='user_update'),
    url(r'^user_delete/(?P<user_id>\d+)/$', 'user_delete', name='user_delete'),
)

kraken/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^kraken/', include('kraken.apps.core.urls', namespace="core")),
    url(r'^kraken/', include('kraken.apps.help.urls', namespace="help")),
    url(r'^kraken/', include('kraken.apps.schemas.urls', namespace="schemas")),
    url(r'^kraken/', include('kraken.apps.users.urls', namespace="users")),
    url(r'^kraken/admin/', include(admin.site.urls)),
)

kraken/apps/core/models.py
import time
from django.db import models


class Client(models.Model):
    """
    Model for client.

    Currently serves as essentially a folder for schemas
    """
    name = models.CharField(max_length=200, unique=True)

    def schemas(self):
        return ClientSchema.objects.filter(client=self).order_by('name')

    def __unicode__(self):
        return self.name


class ClientSchema(models.Model):
    """
    Model for schemas.

    Currently serves as essentially a folder for schema versions
    """
    name = models.CharField(max_length=200)
    client = models.ForeignKey(Client)

    class Meta:
        unique_together = (("name", "client"), )

    def versions(self):
        return SchemaVersion.objects.filter(client_schema=self).order_by('identifier')

    def __unicode__(self):
        return '{0}: {1}'.format(self.client.name, self.name)


class SchemaVersion(models.Model):
    """
    Model for schema versions

    Contains version identifier and delimiter. Individual field constraints for a schema version are
    SchemaColumn objects with a foreign key back to a SchemaVersion.
    """
    # delimiter options
    FIXED = 'Fixed'
    PIPE = 'Pipe'
    COMMA = 'Comma'
    DELIMITER_TYPE_CHOICES = (
        (FIXED, 'Fixed'),
        (PIPE, 'Pipe'),
        (COMMA, 'Comma')
    )

    identifier = models.CharField(max_length=50)
    client_schema = models.ForeignKey(ClientSchema, related_name='schema')
    current = models.BooleanField(default=True)
    delimiter = models.TextField(choices=DELIMITER_TYPE_CHOICES, default=FIXED)

    def __unicode__(self):
        return '{0}: {1}'.format(self.client_schema, self.identifier)

    class Meta:
        unique_together = (("identifier", "client_schema"), )

    def files(self):
        return VersionFile.objects.filter(schema_version=self)

    def schema_fields_total_length(self):
        fields = SchemaColumn.objects.filter(schema_version=self).order_by('position')
        total_length = 0
        for field in fields:
            total_length += field.length

        return total_length

    def get_columns(self, position_order=False):
        """
        Gets a ModelSet of columns from VersionColumn associated with this ClientVersion
        Receives:   position_order (True or False) default (False)
        Returns:    ModelSet
        """
        if position_order:
            return SchemaColumn.objects.filter(schema_version=self).order_by('position')
        return SchemaColumn.objects.filter(schema_version=self)

    def save_columns(self, columns={}):
        """
        Saves ModelSet of columns to database
        Receives:   columns (dict) default (empty dict)
        Returns:    dict
        """
        if columns.get('valid') and columns.get('fields'):
            cols = SchemaColumn.objects.filter(schema_version=self)
            cols_pks = cols.values_list('pk', flat=True)
            columns_pks = [x.pk for x in columns.get('fields')]
            for c in cols_pks:
                if c not in columns_pks:
                    SchemaColumn.objects.get(pk=c).delete()
            for c in columns.get('fields'):
                c.save()
        return columns

    def validate_columns(self, post):
        """
        Populates list of VersionColumn models from fields in form inside Schema Editor template
                and validates columns using model.full_clean()
        Receives:   request.POST
        Returns:    dict
        """
        columns = {'valid': True, 'error_message': None, 'fields': None}
        row_order = post.get('row_order', '').strip()
        field_list = []
        if row_order:
            row_order = row_order.strip().split(' ')
            for i, r in enumerate(row_order):
                try:
                    cid = post.get('hiddenFieldId_' + r)
                    if cid:
                        column = SchemaColumn.objects.get(pk=cid)
                    else:
                        column = SchemaColumn()
                    column.position = i+1
                    column.name = post.get('inputFieldName_' + r)
                    column.length = post.get('inputFieldLength_' + r)
                    column.schema_version = self
                    ftype = post.get('selectFieldType_' + r)
                    if ftype == SchemaColumn.NUMBER:
                        column.type = SchemaColumn.NUMBER
                    elif ftype == SchemaColumn.TEXT:
                        column.type = SchemaColumn.TEXT
                    funique = post.get('checkFieldUnique_' + r)
                    if funique:
                        column.unique = True
                    else:
                        column.unique = False
                    field_list.append(column)
                    column.full_clean()
                except Exception as e:
                    if columns['valid']:
                        columns['valid'] = False
                        columns['error_message'] = 'Custom Fields contain errors'
            columns['fields'] = field_list
            return columns
        return {'valid': None, 'error_message': None, 'fields': None}


def version_file_location(instance, filename):
    return "{0}_{1}".format(str(time.time()).replace('.', ''), filename)


class VersionFile(models.Model):
    name = models.CharField(max_length=200, blank=False)
    schema_version = models.ForeignKey(SchemaVersion)
    last_opened = models.DateTimeField('last opened', auto_now=True)
    contents = models.FileField(upload_to=version_file_location)

    class Meta:
        unique_together = (("name", "schema_version"), )

    def __unicode__(self):
        return '{0}: {1}'.format(self.schema_version, self.name)

    @property
    def file_contents(self):
        f = self.contents
        f.open(mode='rb')
        lines = f.readlines()
        data = ''
        for line in lines:
            data += line
        f.close()

        return data


class FileColumn(models.Model):
    NUMBER = 'Number'
    TEXT = 'Text'
    CUSTOM_LIST = 'Custom List'
    FIRST_NAME = 'First Name'
    LAST_NAME = 'Last Name'
    ADDRESS = 'Address'
    ZIP_CODE = 'ZIP Code'
    GENERATOR_CHOICES = (
        (TEXT, 'Text'),
        (NUMBER, 'Number'),
        (CUSTOM_LIST, 'Custom List'),
        (FIRST_NAME, 'First Name'),
        (LAST_NAME, 'Last Name'),
        (ADDRESS, 'Address'),
        (ZIP_CODE, 'ZIP Code')
    )
    NUMBER_GENERATOR_CHOICES = (
        (NUMBER, 'Number'),
        (CUSTOM_LIST, 'Custom List'),
        (ZIP_CODE, 'ZIP Code')
    )

    version_file = models.ForeignKey('VersionFile')
    schema_column = models.ForeignKey('SchemaColumn')
    generator = models.TextField(choices=GENERATOR_CHOICES, default=TEXT)
    payload = models.TextField()  # JSON objects defining options for chosen generator

    class Meta:
        unique_together = (("version_file", "schema_column"), )

    def __unicode__(self):
        return '{0}: {1}'.format(self.schema_column, self.version_file.name)


class SchemaColumn(models.Model):
    # field type options
    TEXT = 'Text'
    NUMBER = 'Number'
    TYPE_CHOICES = (
        (TEXT, 'Text'),
        (NUMBER, 'Number')
    )

    position = models.IntegerField()
    schema_version = models.ForeignKey(SchemaVersion)
    name = models.CharField(max_length=200, blank=False)
    type = models.TextField(choices=TYPE_CHOICES, default=TEXT)
    length = models.IntegerField()
    unique = models.BooleanField(default=True)

    def __unicode__(self):
        return unicode(self.schema_version) + u" - {0}: {1}".format(self.position, self.name)

    class Meta:
        unique_together = (("name", "schema_version"), )

kraken/apps/core/forms.py
from django import forms
from django.core.exceptions import NON_FIELD_ERRORS
from django.forms import ModelForm, TextInput

from kraken.apps.core.models import Client, ClientSchema, SchemaVersion, VersionFile


class ClientForm(ModelForm):
    class Meta:
        model = Client
        exclude = []

    def __init__(self, *args, **kwargs):
        super(ClientForm, self).__init__(*args, **kwargs)
        self.fields['name'] = forms.CharField(error_messages={
            'required': 'Client Name is required',
            'invalid': 'Client Name is not a valid value',
            'unique': 'Client Name already exists'
        })
        self.fields['name'].widget = TextInput(attrs={
            'placeholder': 'Client Name',
            'class': 'form-control'
        })


class ClientSchemaForm(ModelForm):
    class Meta:
        model = ClientSchema
        exclude = []
        error_messages = {
            NON_FIELD_ERRORS: {
                # 'unique_together': "%(model_name)s's %(field_labels)s are not unique",
                'unique_together': "Schema Name is not unique",
            }
        }

    def __init__(self, *args, **kwargs):
        super(ClientSchemaForm, self).__init__(*args, **kwargs)
        self.fields['name'] = forms.CharField(error_messages={
            'required': 'Schema Name is required',
            'invalid': 'Schema Name is not a valid value'
        })
        self.fields['name'].widget = TextInput(attrs={
            'placeholder': 'Schema Name',
            'class': 'form-control'
        })


class SchemaVersionForm(ModelForm):
    class Meta:
        model = SchemaVersion
        exclude = ['client_schema', 'current']
        error_messages = {
            NON_FIELD_ERRORS: {
                # 'unique_together': "%(model_name)s's %(field_labels)s are not unique",
                'unique_together': "Version is not unique",
            }
        }

    def __init__(self, *args, **kwargs):
        super(SchemaVersionForm, self).__init__(*args, **kwargs)
        self.fields['identifier'] = forms.CharField(error_messages={
            'required': 'Version is required',
            'invalid': 'Version is not a valid value'
        })
        self.fields['identifier'].widget = TextInput(attrs={
            'placeholder': 'Example: Identifier',
            'class': 'form-control'
        })
        self.fields['delimiter'] = forms.ChoiceField(
            widget=forms.RadioSelect,
            choices=SchemaVersion.DELIMITER_TYPE_CHOICES
        )


class VersionFileForm(ModelForm):
    class Meta:
        model = VersionFile
        exclude = ['schema_version', 'last_opened', 'contents']

    def __init__(self, *args, **kwargs):
        super(VersionFileForm, self).__init__(*args, **kwargs)
        self.fields['name'] = forms.CharField(error_messages={
            'required': 'File Name field is required',
            'invalid': 'File Name field is not a valid value'
        })
        self.fields['name'].widget = TextInput(attrs={
            'placeholder': 'File Name',
            'class': 'form-control'
        })

kraken/apps/core/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import json
from django.http import HttpResponse, HttpResponseNotFound
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_exempt

from kraken.apps.core.models import Client, ClientSchema
from kraken.apps.core import messages
from kraken.apps.core.forms import ClientForm


@login_required
def home(request):
    clients = Client.objects.all().order_by('name')
    context = {
        'clients': clients,
        'form': ClientForm()
    }
    return render(request, 'core/home.html', context)


def landing(request):
    if request.user.is_authenticated():
        return redirect('core:home')
    return render(request, 'core/landing.html')


def sign_in(request):
    if request.method == "POST":
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user:
            if user.is_active:
                login(request, user)

                if request.GET.get('next'):
                    return redirect(request.GET['next'])
                else:
                    return redirect('core:home')
            else:
                messages.danger(request, 'This account is inactive.')
                return redirect('core:landing')
        else:
            messages.danger(request, 'Invalid username or password.')
            return redirect('core:landing')
    else:
        return redirect('core:landing')


@login_required
def sign_out(request):
    logout(request)
    return redirect('core:landing')


@login_required
@csrf_exempt
def create_client(request):
    """
    Handle create new client with valid client name
    :param request:
    :return: if succeed, back to home
             if un-succeed, back to create client modal with error message
    """
    if request.method == "POST":
        form = ClientForm(request.POST)
        try:
            if form.is_valid():
                client = form.save()
                messages.success(request, 'Client \"{0}\" has been created.'.format(client.name))
                return HttpResponse(json.dumps({'success': True}))
            else:
                context = {
                    'success': False,
                }
                if form['name'].errors:
                    context['error'] = form['name'].errors
        except Exception as e:
            context = {
                'success': False,
                'error': e.message
            }

        return HttpResponse(json.dumps(context))
    else:
        redirect('core:home')

kraken/apps/core/templates/core/footer.html
{%  block footer %}
    <div id="footer">
        <p class="text-right text-muted">
            v 1.0.0.13 | Powered by Quality Engineering & Innovation |
            <i class="fa fa-bell" style="color: lightseagreen;"></i>&nbsp;<a
                    href="http://jira.west.com/browse/krak">Report</a>&nbsp;|&nbsp;
            <i class="fa fa-envelope text-primary" style="color: lightseagreen;"></i>&nbsp;<a
                    href="mailto:QEIInnovation@west.com?subject=Kraken Feedback">Contact</a>&nbsp;|&nbsp;
            <i class="fa fa-question" style="color: lightseagreen;"></i>&nbsp;<a href="{% url 'help:help_faq' %}">FAQ</a>
        </p>
    </div>
{% endblock %}

kraken/apps/core/templates/core/header.html
{% block header %}
    <header id="navbar" class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'core:home' %}"><i class="fa fa-home fa-fw"></i>&nbsp;Kraken</a>
        </div>
        {% if user.is_authenticated %}
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
{#                    <li><a href="#" class="dropdown-toggle" data-toggle="popover" title="Client Navigator" tabindex="0">#}
{#                        <i class="fa fa-link fa-fw"></i>&nbsp;Clients</a></li>#}
                    <li><a href="{% url 'help:help_guide' %}"><i class="fa fa-thumbs-o-up fa-fw"></i>&nbsp;Help</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            {% if user.first_name %}
                                <i class="fa fa-user fa-fw"></i>&nbsp;Welcome,&nbsp;{{ user.first_name }}&nbsp;<i class="fa fa-caret-down fa-fw"></i>
                            {% else %}
                                <i class="fa fa-user fa-fw"></i>&nbsp;Welcome,&nbsp;{{ user.username }}&nbsp;<i class="fa fa-caret-down fa-fw"></i>
                            {% endif %}
                        </a>
                        <ul class="dropdown-menu navbar-dropdown-menu">
                            {% if user.is_superuser %}
                                <li><a href="{% url 'users:user_management' %}"><i class="fa fa-wrench fa-fw"></i>&nbsp;User Management</a></li>
                                <li><a href="{% url 'admin:index' %}" target="_blank"><i class="fa fa-cogs fa-fw"></i>&nbsp;Django Admin</a></li>
                            {% endif %}
                            <li><a href="{% url 'core:sign_out' %}"><i class="fa fa-sign-out fa-fw"></i>&nbsp;Sign Out</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        {% endif %}
    </header>
{% endblock %}

kraken/apps/core/templates/core/home.html
{% extends 'core/base.html' %}
{% block title %}Home{% endblock %}
{% block headscript %}

{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12 text-center">
                <h3>Client Navigator</h3>
            </div>
        </div>
        <br>

        <div class="row">
            <div class="col-xs-12">
                <div id="clientNavigator">
                <div id="columns"></div>
                </div>
            </div>
        </div>
    </div>

    {% include 'core/modal_client.html' %}

{% endblock %}
{% block endscript %}
    <script type="text/javascript">

        {% include 'core/core.js' %}

        $(function () {
            $("#columns").hColumns({
                nodeSource: function(node_id, callback) {
                    // callback is a function that receive two parameter
                    // callback(error, array of nodes);

                    var clientIdPrefix = 1000000;
                    var schemaIdPrefix = 2000000;
                    var versionIdPrefix = 3000000;
                    var fileIdPrefix = 4000000;
                    var editVersion = 5000000;

                    // if inital load
                    if(node_id === null) {
                        return callback(null, [
                            {% if user.is_staff %}{ id: clientIdPrefix, label: "New Client", type: "create_client" },{% endif %}
                            {% for client in clients %}
                                { id: clientIdPrefix + {{ client.id }}, label: "{{ client.name|safe|addslashes }}", type: "folder" },
                            {% endfor %}
                        ]);
                    }

                    {% for client in clients %}
                        if(node_id === clientIdPrefix + {{ client.id }}) {
                            return callback(null, [
                                {% if user.is_staff %}{ id: schemaIdPrefix, label: "New Schema", type: "create", url: "{% url 'schemas:create_schema' client.id %}" },{% endif %}
                                {% for schema in client.schemas %}
                                    { id: schemaIdPrefix + {{ schema.id }}, label: "{{ schema.name|safe|addslashes }}", type: "folder" },
                                {% endfor %}
                            ]);
                        }
                        {% for schema in client.schemas %}
                            if (node_id === schemaIdPrefix + {{ schema.id }}) {
                                return callback(null, [
{#                                    { id: versionIdPrefix, label: "New Version", type: "create", url: "{% url 'schemas:create_version' client.id schema.id %}" },#}
                                    {% for version in schema.versions %}
                                        { id: versionIdPrefix + {{ version.id }}, label: "{{ version.identifier }}", type: "folder" },
                                    {% endfor %}
                                ]);
                            }
                            {% for version in schema.versions %}
                                if (node_id === versionIdPrefix + {{ version.id }}) {
                                    return callback(null, [
                                        {% if user.is_staff %}{ id: editVersion, label: "New/Edit Version", type: "edit", url: "{% url 'schemas:edit_version' client.id schema.id version.id %}" },{% endif %}
                                        { id: fileIdPrefix, label: "New File", type: "create", url: "{% url 'schemas:create_file' client.id schema.id version.id %}" },
                                        {% for file in version.files %}
{#                                            { id: fileIdPrefix + {{ file.id }}, label: "{{ file.name }}", type: "file", url: "{% url 'schemas:download_file' client.id schema.id version.id file.id %}" },#}
                                            { id: fileIdPrefix + {{ file.id }}, label: "{{ file.name|safe|addslashes }}", type: "file", url: "{% url 'schemas:edit_file' client.id schema.id version.id file.id %}" },
                                        {% endfor %}
                                    ]);
                                }
                            {% endfor %}
                        {% endfor %}
                    {% endfor %}
                }
            });
        });
    </script>
{% endblock %}

kraken/apps/core/templates/core/landing.html
{% extends 'core/base.html' %}
{% block title %}Sign In{% endblock %}
{% block headscript %}

{% endblock %}
{% block content %}
<div class="container">
    <div class="col-xs-3"></div>
    <div class="col-xs-6">
{#        <div class="row text-center">#}
{#            <img src="{{ STATIC_URL }}kraken/Kraken_logo.jpg" style="width:256px;height: 220px">#}
{#        </div>#}
        <div class="well" id="landing-well" style="margin-top: 25px;">
            <h3 class="text-center text-muted">
                <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x" style="color: #ef0000;"></i>
                    <i class="fa fa-sign-in fa-stack-1x fa-inverse"></i>
                </span>
                <br><br>
                Sign into <span style="color: #ef0000;">Kraken</span>
            </h3>
            <hr>
            <div>
                <form class="form" role="form" method=POST action="{% url 'core:sign_in' %}{% if request.GET.next %}?next={{ request.GET.next }}{% endif %}">
                    <div class="input-group" style="margin-bottom: 10px;">
                        <span class="input-group-addon"><i class="fa fa-user fa-fw"></i></span>
                        <input type="text" class="form-control" name="username" id="username" placeholder="Username" tabindex="1">
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-key fa-fw"></i></span>
                        <input type="password" class="form-control" name="password" id="password" placeholder="Password" tabindex="2">
                    </div>
                    <p class="help-block text-center">Please use your Active Directory credentials.</p>
                    <hr>
                    <div class="form-group col-xs-6">

                    </div>
                    <div class="form-group col-xs-6">
                        <button type="submit" class="btn btn-primary btn-block" tabindex="4">Sign In</button>
                    </div>
                    {% csrf_token %}
                </form>
            </div>
            <br><br><br>
        </div>
    </div>
    <div class="col-xs-3"></div>
</div>
{% endblock %}
{% block endscript %}
    <script type="text/javascript">
        $(function () {
            $('#username').focus();
            $('#username').select();
        });
    </script>
{% endblock %}

kraken/apps/core/templates/core/modal_client.html
<!--Create Client modal -->
<div id="modal_create_client" class="modal fade">
    <div class="modal-dialog">
        <form method="post" action="" id="modal_create_client_form">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Create Client</h4>
                </div>
                <div class="modal-body">

                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="modal_edit_client_input_name">
                                Client Name
                                <span class="text-red">*</span>
                            </label>
                            {{ form.name }}

                        </div>
                    </div>

                    <br>
                    <div class="col-lg-12">
                        <p id="modal_create_client_error" style="color: red"></p>
                    </div>
                    {% csrf_token %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Create</button>
                </div>
            </div>
        </form>
    </div>
</div>


<!--Idle Time Out Modal -->
<div id="idle_time_out" class="modal fade">
    <div class="modal-dialog">
        <form method="post" action="{% url 'core:sign_out' %}" id="modal_sign_out_form">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Session Time Out Issue</h4>
                </div>
                <div class="modal-body">

                    <div class="col-lg-12">
                        <div class="form-group" style="color: red">
                            You are not authorized to perform this operation.
                            Close this dialog and log in.
                        </div>
                    </div>
                    {% csrf_token %}
                </div>
                <div class="modal-footer">
{#                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>#}
                    <button type="submit" class="btn btn-primary">Close</button>
                </div>
            </div>
        </form>
    </div>
</div>