kraken/apps/schemas/urls.py
from django.conf.urls import patterns, url

from kraken.apps.schemas import views

urlpatterns = patterns('kraken.apps.schemas.views',
                       url(r'^clients/(?P<client_id>\d+)/schemas/create/$', 'create_schema', name='create_schema'),
                       url(r'^clients/(?P<client_id>\d+)/schemas/(?P<schema_id>\d+)/versions/(?P<version_id>\d+)/edit/$', 'edit_version', name='edit_version'),
                       url(r'^clients/(?P<client_id>\d+)/schemas/(?P<schema_id>\d+)/versions/(?P<version_id>\d+)/files/create/$', 'create_file', name='create_file'),
                       url(r'^clients/(?P<client_id>\d+)/schemas/(?P<schema_id>\d+)/versions/(?P<version_id>\d+)/files/(?P<file_id>\d+)/edit/$', 'edit_file', name='edit_file'),

                       url(r'^client/(?P<client_name>\w+)/schemas/$', views.client_schemas_list, name='client_schemas_list'),
                       url(r'^client/(?P<client_name>\w+)/schema/(?P<schema_name>\w+)/versions/$', views.schema_versions_list, name='schema_versions_list'),
                       url(r'^schemas/batch_files/$', 'batch_files', name='batch_files'),

                       )

kraken/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^kraken/', include('kraken.apps.core.urls', namespace="core")),
    url(r'^kraken/', include('kraken.apps.help.urls', namespace="help")),
    url(r'^kraken/', include('kraken.apps.schemas.urls', namespace="schemas")),
    url(r'^kraken/', include('kraken.apps.users.urls', namespace="users")),
    url(r'^kraken/admin/', include(admin.site.urls)),
)

kraken/apps/core/models.py
import time
from django.db import models


class Client(models.Model):
    """
    Model for client.

    Currently serves as essentially a folder for schemas
    """
    name = models.CharField(max_length=200, unique=True)

    def schemas(self):
        return ClientSchema.objects.filter(client=self).order_by('name')

    def __unicode__(self):
        return self.name


class ClientSchema(models.Model):
    """
    Model for schemas.

    Currently serves as essentially a folder for schema versions
    """
    name = models.CharField(max_length=200)
    client = models.ForeignKey(Client)

    class Meta:
        unique_together = (("name", "client"), )

    def versions(self):
        return SchemaVersion.objects.filter(client_schema=self).order_by('identifier')

    def __unicode__(self):
        return '{0}: {1}'.format(self.client.name, self.name)


class SchemaVersion(models.Model):
    """
    Model for schema versions

    Contains version identifier and delimiter. Individual field constraints for a schema version are
    SchemaColumn objects with a foreign key back to a SchemaVersion.
    """
    # delimiter options
    FIXED = 'Fixed'
    PIPE = 'Pipe'
    COMMA = 'Comma'
    DELIMITER_TYPE_CHOICES = (
        (FIXED, 'Fixed'),
        (PIPE, 'Pipe'),
        (COMMA, 'Comma')
    )

    identifier = models.CharField(max_length=50)
    client_schema = models.ForeignKey(ClientSchema, related_name='schema')
    current = models.BooleanField(default=True)
    delimiter = models.TextField(choices=DELIMITER_TYPE_CHOICES, default=FIXED)

    def __unicode__(self):
        return '{0}: {1}'.format(self.client_schema, self.identifier)

    class Meta:
        unique_together = (("identifier", "client_schema"), )

    def files(self):
        return VersionFile.objects.filter(schema_version=self)

    def schema_fields_total_length(self):
        fields = SchemaColumn.objects.filter(schema_version=self).order_by('position')
        total_length = 0
        for field in fields:
            total_length += field.length

        return total_length

    def get_columns(self, position_order=False):
        """
        Gets a ModelSet of columns from VersionColumn associated with this ClientVersion
        Receives:   position_order (True or False) default (False)
        Returns:    ModelSet
        """
        if position_order:
            return SchemaColumn.objects.filter(schema_version=self).order_by('position')
        return SchemaColumn.objects.filter(schema_version=self)

    def save_columns(self, columns={}):
        """
        Saves ModelSet of columns to database
        Receives:   columns (dict) default (empty dict)
        Returns:    dict
        """
        if columns.get('valid') and columns.get('fields'):
            cols = SchemaColumn.objects.filter(schema_version=self)
            cols_pks = cols.values_list('pk', flat=True)
            columns_pks = [x.pk for x in columns.get('fields')]
            for c in cols_pks:
                if c not in columns_pks:
                    SchemaColumn.objects.get(pk=c).delete()
            for c in columns.get('fields'):
                c.save()
        return columns

    def validate_columns(self, post):
        """
        Populates list of VersionColumn models from fields in form inside Schema Editor template
                and validates columns using model.full_clean()
        Receives:   request.POST
        Returns:    dict
        """
        columns = {'valid': True, 'error_message': None, 'fields': None}
        row_order = post.get('row_order', '').strip()
        field_list = []
        if row_order:
            row_order = row_order.strip().split(' ')
            for i, r in enumerate(row_order):
                try:
                    cid = post.get('hiddenFieldId_' + r)
                    if cid:
                        column = SchemaColumn.objects.get(pk=cid)
                    else:
                        column = SchemaColumn()
                    column.position = i+1
                    column.name = post.get('inputFieldName_' + r)
                    column.length = post.get('inputFieldLength_' + r)
                    column.schema_version = self
                    ftype = post.get('selectFieldType_' + r)
                    if ftype == SchemaColumn.NUMBER:
                        column.type = SchemaColumn.NUMBER
                    elif ftype == SchemaColumn.TEXT:
                        column.type = SchemaColumn.TEXT
                    funique = post.get('checkFieldUnique_' + r)
                    if funique:
                        column.unique = True
                    else:
                        column.unique = False
                    field_list.append(column)
                    column.full_clean()
                except Exception as e:
                    if columns['valid']:
                        columns['valid'] = False
                        columns['error_message'] = 'Custom Fields contain errors'
            columns['fields'] = field_list
            return columns
        return {'valid': None, 'error_message': None, 'fields': None}


def version_file_location(instance, filename):
    return "{0}_{1}".format(str(time.time()).replace('.', ''), filename)


class VersionFile(models.Model):
    name = models.CharField(max_length=200, blank=False)
    schema_version = models.ForeignKey(SchemaVersion)
    last_opened = models.DateTimeField('last opened', auto_now=True)
    contents = models.FileField(upload_to=version_file_location)

    class Meta:
        unique_together = (("name", "schema_version"), )

    def __unicode__(self):
        return '{0}: {1}'.format(self.schema_version, self.name)

    @property
    def file_contents(self):
        f = self.contents
        f.open(mode='rb')
        lines = f.readlines()
        data = ''
        for line in lines:
            data += line
        f.close()

        return data


class FileColumn(models.Model):
    NUMBER = 'Number'
    TEXT = 'Text'
    CUSTOM_LIST = 'Custom List'
    FIRST_NAME = 'First Name'
    LAST_NAME = 'Last Name'
    ADDRESS = 'Address'
    ZIP_CODE = 'ZIP Code'
    GENERATOR_CHOICES = (
        (TEXT, 'Text'),
        (NUMBER, 'Number'),
        (CUSTOM_LIST, 'Custom List'),
        (FIRST_NAME, 'First Name'),
        (LAST_NAME, 'Last Name'),
        (ADDRESS, 'Address'),
        (ZIP_CODE, 'ZIP Code')
    )
    NUMBER_GENERATOR_CHOICES = (
        (NUMBER, 'Number'),
        (CUSTOM_LIST, 'Custom List'),
        (ZIP_CODE, 'ZIP Code')
    )

    version_file = models.ForeignKey('VersionFile')
    schema_column = models.ForeignKey('SchemaColumn')
    generator = models.TextField(choices=GENERATOR_CHOICES, default=TEXT)
    payload = models.TextField()  # JSON objects defining options for chosen generator

    class Meta:
        unique_together = (("version_file", "schema_column"), )

    def __unicode__(self):
        return '{0}: {1}'.format(self.schema_column, self.version_file.name)


class SchemaColumn(models.Model):
    # field type options
    TEXT = 'Text'
    NUMBER = 'Number'
    TYPE_CHOICES = (
        (TEXT, 'Text'),
        (NUMBER, 'Number')
    )

    position = models.IntegerField()
    schema_version = models.ForeignKey(SchemaVersion)
    name = models.CharField(max_length=200, blank=False)
    type = models.TextField(choices=TYPE_CHOICES, default=TEXT)
    length = models.IntegerField()
    unique = models.BooleanField(default=True)

    def __unicode__(self):
        return unicode(self.schema_version) + u" - {0}: {1}".format(self.position, self.name)

    class Meta:
        unique_together = (("name", "schema_version"), )

kraken/apps/schemas/templates/schemas/modal_version.html
<!--Create or Save Version modal -->
<div id="modal_create_version" class="modal fade">
    <div class="modal-dialog">
        <form method="post" action="" id="modal_create_version_form">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Create Version or Save Version?</h4>
                </div>
                <div class="modal-body">

                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="modal_old_version_identifier">
                                Old Identifier:
                            </label>
                            <p>{{ version.identifier }}</p>
                            <br>
                            <label for="modal_new_version_identifier">
                                New Identifier:
                            </label>
                            <p id="modal_version_name_new_display"></p>
                            <input id="modal_version_name" name="modal_version_name" value="" hidden>

                        </div>
                    </div>
                    <br>

                    {% csrf_token %}
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-success" name="save_version">Save</button>
                    <button type="submit" class="btn btn-success" name="create_version">Create</button>
                </div>
            </div>
        </form>
    </div>
</div>

kraken/apps/schemas/templates/schemas/schema_editor.html
{% extends 'core/base.html' %}
{% block title %}Schema Editor{% endblock %}
{% block headscript %}

{% endblock %}
{% block content %}
    <div class="container">
        {% if state == 'edit' %}
        <form id="formSchema" action="{% url 'schemas:edit_version' client.id schema.id version.id %}" method="POST">
        {% else %}
        <form id="formSchema" action="{% url 'schemas:create_schema' client.id %}" method="POST">
        {% endif %}
            {% csrf_token %}
            <input type="hidden" name="client_id" value="{{ client.id }}">
            <input type="hidden" name="state" value="{{ state }}">
            <input type="hidden" name="row_order" value="">

            <div class="row">
                <div class="col-xs-8">
                    <h3>{{ client.name }}</h3>
                </div>
                <div class="col-xs-2">
                    <button name="update_viewer" class="btn btn-primary" style="width: 100%;">
                        <i class="fa fa-refresh"></i>&nbsp;Refresh
                    </button>
                </div>
                <div class="col-xs-2">
                    <button type="submit" name="save_schema" class="btn btn-primary" style="width: 100%;">
                        <i class="fa fa-floppy-o"></i>&nbsp;Save
                    </button>
                </div>
            </div>
            <br>

            <div class="row">
                <div class="col-xs-12">
                    <textarea class="form-control" rows="5" id="textareaViewer"
                              style="font-family: 'courier new', monospace; background-color: #ffffff; cursor: auto;" readonly></textarea>
                </div>
            </div>
            <br>

            <div class="row">
                <div class="col-xs-6">
                    <div class="form-group">
                        <label class="control-label" for="inputSchemaName">Schema Name</label>
                        {{ schema_form.name }}
                        <input id="id_client" name="client" value="{{ client.id }}" hidden>
                    </div>
                </div>
                <div class="col-xs-4">
                    <div class="form-group">
                        <label class="control-label col-xs-12">Delimiter</label>

                        <table id="tableDelimiter" class="col-xs-12">
                            <tr>
                                {% for choice in version_form.delimiter %}
                                    <td class="col-xs-4" style="line-height: 38px;">

                                        {{ choice.tag }} &nbsp;<strong>{{ choice.choice_label }}</strong>
                                    </td>
                                {% endfor %}

                            </tr>
                        </table>
                    </div>
                </div>
                <div class="col-xs-2">
                    <div class="form-group">
                        <label class="control-label" for="inputVersion">Version</label>
                        {{ version_form.identifier }}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    <table id="tableFields" class="table table-hover sort">
                        <thead>
                        <tr>
                            <th class="col-xs-5">
                                Field Name
                            </th>
                            <th class="col-xs-2">
                                Length
                            </th>
                            <th class="col-xs-2">
                                Type
                            </th>
{#                            <th class="col-xs-1 text-center">#}
{#                                Unique#}
{#                            </th>#}
                            <th class="col-xs-1">

                            </th>
                            <th class="col-xs-1">
                                <button id="buttonAddField" class="btn btn-success btn-xs" style="width: 100%;">Add Field
                                </button>
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </form>
    </div>

    {% include 'schemas/modal_version.html' %}

{% endblock %}
{% block endscript %}
    <script type="text/javascript">
        var counter = 0;
        var unsavedChanges = false;

        function formChangeHandler() {
            unsavedChanges = true;
        }

        var sortableHelper = function (e, ui) {
            ui.children().each(function () {
                $(this).width($(this).width());
            });
            return ui;
        };

        function deleteRow(row) {
            //event.preventDefault();
            formChangeHandler();
            $(row).closest('tr').remove();
        }

        function updateViewer() {
            var delimiterType = $("#tableDelimiter input[type='radio']:checked").val();
            delimiter = ''; // for Fixed
            if (delimiterType == 'Pipe') {
                delimiter = '|';
            } else if (delimiterType == 'Comma') {
                delimiter = ',';
            }
            var s = "";
            $("#tableFields tbody tr").each(function() {
                var fieldName = $(this).find("input[name^='inputFieldName']").val();
                s += fieldName + delimiter;
            });
            var len = delimiter.length;
            s = s.substring(0, s.length - len);
            $('#textareaViewer').val(s);
        }

        $("button[name='update_viewer']").on('click', function (event) {
            event.preventDefault();
            updateViewer();
        })

        $("button[name='save_schema']").on('click', function (event) {
            var s = "";
            $("#tableFields tbody tr").each(function() {
                s = s + this.id + " ";
            });
            $('input[name="row_order"]').val(s);

            var version_name_new = $("input[name='identifier']").val();
            var delimiterType = $("#tableDelimiter input[type='radio']:checked").val();

            if (( '{{ version.identifier }}' != version_name_new ) &&
                    ( '{{ schema.name }}' == $("input[name='name']").val()) &&
                    ( delimiterType == '{{ version.delimiter }}')) {
                event.preventDefault();
                $('#modal_version_name_new_display').html(version_name_new);
                $('#modal_version_name').val(version_name_new);
                $('#modal_create_version').modal('show');
            }
            unsavedChanges = false;
        });

        function populateFields() {
            {% for f in fields %}
                counter++;
                $('table#tableFields').append($(
                    '<tr id="' + counter + '">' +
                    '<td>' +
                    '<input type="hidden" name="hiddenFieldId_' + counter + '" value="{% if f.id %}{{ f.id }}{% endif %}">' +
                    '<input type="text" onchange="formChangeHandler();" class="form-control" name="inputFieldName_' + counter + '" placeholder="Field Name" value="{{ f.name }}">' +
                    '</td>' +
                    '<td>' +
                    '<input type="text" onchange="formChangeHandler();" class="form-control" name="inputFieldLength_' + counter + '" placeholder="10" value="{{ f.length }}">' +
                    '</td>' +
                    '<td>' +
                    '<select onchange="formChangeHandler();" class="form-control" name="selectFieldType_' + counter + '">' +
                    '<option{% if f.type == "Text" %} selected{% endif %}>Text</option>' +
                    '<option{% if f.type == "Number" %} selected{% endif %}>Number</option>' +
                    '</select>' +
                    '</td>' +
{#                    '<td class="text-center" style="line-height: 38px;">' +#}
{#                    '<input type="checkbox" name="checkFieldUnique_' + counter + '"{% if f.unique %} checked{% endif %}>' +#}
{#                    '</td>' +#}
                    '<td class="text-center" style="line-height: 38px;">' +
                    '<i class="fa fa-arrows fa-lg" style="cursor: move;"></i>' +
                    '</td>' +
                    '<td class="text-center" style="line-height: 38px;">' +
                    '<a href="#" onclick="deleteRow(this);"><i class="fa fa-trash-o fa-lg"></i></a>' +
                    '</td>' +
                    '</tr>'
                ));

            {% endfor %}

            sortable_edit_ff();
        }

        // Jquery UI Sortable disableSelection Firefox issue
        function sortable_edit_ff() {
            $('input[type=text]').bind('mousedown.ui-disableSelection selectstart.ui-disableSelection', function(event) {
                event.stopImmediatePropagation();
            });

            $('select').bind('mousedown.ui-disableSelection selectstart.ui-disableSelection', function(event) {
                event.stopImmediatePropagation();
            });
        }

        $(function () {
            $("input").change(function(){
                formChangeHandler();
            });

            $(".sort tbody").sortable({
                helper: sortableHelper
            }).disableSelection();

            $(window).bind('beforeunload', function () {
                if (unsavedChanges) {
                    return 'There are unsaved changes.';
                }
            });

            $('#buttonAddField').click(function (event) {
                event.preventDefault();
                unsavedChanges = true;
                counter++;
                var newRow = $('<tr id="' + counter + '">' +
                            '<td>' +
                            '<input type="text" onchange="formChangeHandler();" class="form-control" name="inputFieldName_' + counter + '" placeholder="Field Name">' +
                            '</td>' +
                            '<td>' +
                            '<input type="text" onchange="formChangeHandler();" class="form-control" name="inputFieldLength_' + counter + '" placeholder="Example: 10 digits">' +
                            '</td>' +
                            '<td>' +
                            '<select onchange="formChangeHandler();" class="form-control" name="selectFieldType_' + counter + '">' +
                            '<option>Text</option>' +
                            '<option>Number</option>' +
                            '</select>' +
                            '</td>' +
{#                            '<td class="text-center" style="line-height: 38px;">' +#}
{#                            '<input type="checkbox" name="checkFieldUnique_' + counter + '">' +#}
{#                            '</td>' +#}
                            '<td class="text-center" style="line-height: 38px;">' +
                            '<i class="fa fa-arrows fa-lg" style="cursor: move;"></i>' +
                            '</td>' +
                            '<td class="text-center" style="line-height: 38px;">' +
                            '<a href="#" onclick="deleteRow(this);"><i class="fa fa-trash-o fa-lg"></i></a>' +
                            '</td>' +
                            '</tr>');
                $('table#tableFields').append(newRow);

                sortable_edit_ff();
            });

            populateFields();
        });
    </script>
{% endblock %}