kraken/apps/users/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('kraken.apps.users.views',
    url(r'^user_management/$', 'user_management', name='user_management'),
    url(r'^user_update/(?P<user_id>\d+)/$', 'user_update', name='user_update'),
    url(r'^user_delete/(?P<user_id>\d+)/$', 'user_delete', name='user_delete'),
)

kraken/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^kraken/', include('kraken.apps.core.urls', namespace="core")),
    url(r'^kraken/', include('kraken.apps.help.urls', namespace="help")),
    url(r'^kraken/', include('kraken.apps.schemas.urls', namespace="schemas")),
    url(r'^kraken/', include('kraken.apps.users.urls', namespace="users")),
    url(r'^kraken/admin/', include(admin.site.urls)),
)

kraken/apps/users/views.py
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.models import User
from django.contrib.auth import logout
from django.http import HttpResponseNotFound
from django.shortcuts import render, redirect, get_object_or_404


def user_is_superuser(user):
    return user.is_superuser


@user_passes_test(user_is_superuser)
def user_management(request):
    if request.method == 'GET':

        sort_types = [
            'username',
            '-username',
            'last_login',
            '-last_login'
        ]
        users = ''
        sort = request.GET.get('sort', '')
        sort = sort if sort else 'username'

        if sort in sort_types:
            if sort == 'username':
                users = User.objects.all().order_by('username')
            elif sort == '-username':
                users = User.objects.all().order_by('-username')
            elif sort == 'last_login':
                users = User.objects.all().order_by('last_login')
            elif sort == '-last_login':
                users = User.objects.all().order_by('-last_login')

        current_user_id = request.user.id

        context = {
            'users': users,
            'sort': sort,
            'current_user_id': current_user_id
        }

        return render(request, 'users/user_management.html', context)

    return HttpResponseNotFound()


@user_passes_test(user_is_superuser)
def user_update(request, user_id):
    if request.method == "POST":
        user = get_object_or_404(User, pk=user_id)

        user.is_active = request.POST.get('is_active', False) \
            or request.POST.get('is_staff', False) \
            or request.POST.get('is_superuser', False)
        user.is_staff = request.POST.get('is_staff', False) \
            or request.POST.get('is_superuser', False)
        user.is_superuser = request.POST.get('is_superuser', False)

        user.save()

        return redirect('users:user_management')
    else:
        return redirect('users:user_management')


@user_passes_test(user_is_superuser)
def user_delete(request, user_id):
    user = get_object_or_404(User, pk=user_id)

    if user == request.user:
        logout(request)
        user.delete()
        return redirect('core:landing')
    else:
        user.delete()
        return redirect('users:user_management')

kraken/apps/users/templates/users/user_management.html
{% extends 'core/base.html' %}
{% block title %}User Management{% endblock %}
{% block headscript %}

{% endblock %}
{% block content %}
        <div class="container"><br>
        <table class="table table-hover table-condensed">
            <thead>
                <tr>
                    <th class="col-xs-2">
                        {% if sort == 'username' %}
                            <a href="{% url 'users:user_management' %}?sort=-username">
                            <strong>Username</strong></a>&nbsp;<i class="fa fa-sort-asc"></i>
                        {% elif sort == '-username' %}
                            <a href="{% url 'users:user_management' %}?sort=username">
                            <strong>Username</strong></a>&nbsp;<i class="fa fa-sort-desc"></i>
                        {% else %}
                            <a href="{% url 'users:user_management' %}?sort=username">
                            <strong>Username</strong></a>&nbsp;<i class="fa fa-sort"></i>
                        {% endif %}
                    </th>
                    <th class="col-xs-2">First Name</th>
                    <th class="col-xs-2">Last Name</th>
                    <th class="col-xs-2">
                        {% if sort == 'last_login' %}
                            <a href="{% url 'users:user_management' %}?sort=-last_login">
                            <strong>Last Login</strong></a>&nbsp;<i class="fa fa-sort-asc"></i>
                        {% elif sort == '-last_login' %}
                            <a href="{% url 'users:user_management' %}?sort=last_login">
                            <strong>Last Login</strong></a>&nbsp;<i class="fa fa-sort-desc"></i>
                        {% else %}
                            <a href="{% url 'users:user_management' %}?sort=last_login">
                            <strong>Last Login</strong></a>&nbsp;<i class="fa fa-sort"></i>
                        {% endif %}
                    </th>
                    <th class="col-xs-1" style="text-align: center;"><strong>Active</strong></th>
                    <th class="col-xs-1" style="text-align: center;"><strong>Staff</strong></th>
                    <th class="col-xs-1" style="text-align: center;"><strong>Superuser</strong></th>
                    <th class="col-xs-1" style="text-align: center;"><strong>Update</strong></th>
                </tr>
            </thead>
            {% for user in users %}
                {% if user.last_name %}
                <form method="post" action="{% url 'users:user_update' user.id %}">
                    <tr>
                        <td>{{ user.username }}</td>
                        <td>{{ user.first_name }}</td>
                        <td>{{ user.last_name }}</td>
                        <td>{{ user.last_login }}</td>
                        <td style="text-align: center;">
                            <input type="checkbox" name="is_active" {% if user.is_active %}checked{% endif %}>
                        </td>
                        <td style="text-align: center;">
                            <input type="checkbox" name="is_staff" {% if user.is_staff %}checked{% endif %}>
                        </td>
                        <td style="text-align: center;">
                            <input type="checkbox" name="is_superuser" {% if user.is_superuser %}checked{% endif %}>
                        </td>
                        <td style="text-align: center;">
                            {% csrf_token %}
                            <button class="btn btn-primary btn-xs" type="submit">
                                <i class="fa fa-refresh"></i>
                            </button>

                            <a href="#" class="btn btn-danger btn-xs" onclick="deleteModal('{{ user.username }}', {{ user.id }})">
                                <i class="fa fa-trash-o"></i>
                            </a>
                        </td>
                    </tr>
                </form>
                {% endif %}
            {% endfor %}
        </table>
    </div>


    <!--Delete User confirmation modal -->
    <div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" aria-labelledby="deleteTitle" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 id="deleteTitle" class="modal-title"></h4>
                </div>
                <div class="modal-body">
                    <p id="deleteBody">
                        This action will remove this user and <strong>cannot</strong> be undone.
                        The next time the user logs in, their profile will be created using default settings.
                    </p>
                    <p id="deleteSelfWarning" class="text-danger">
                        You are about to delete <strong>YOUR</strong> profile and will be logged out!
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <a href="" id="deleteProfileButton" type="button" class="btn btn-danger">Delete Profile</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block endscript %}
    <script type="text/javascript">
        function deleteModal (username, user_id) {
            $('#deleteTitle').text('Delete user: \"' + username + '\" ?');
            $('#deleteProfileButton').attr('href', '/kraken/user_delete/' + user_id);
            if (user_id == {{ current_user_id }}) {
                $('#deleteSelfWarning').show();
            } else {
                $('#deleteSelfWarning').hide();
            }
            $('#confirmModal').modal('show');
        }

        $(function () {

        });
    </script>
{% endblock %}